### ISSUE TITLE
TypeError: set_options() got an unexpected keyword argument 'task_key

### ISSUE THREAD

**Issue by endejoli** [rrey/ansible-callback-grafana-annotations#12]
I am getting below error while executing the playbook with ansible_annotation callback enabled

Ansible version: 2.7.12 
$ cat ansible.cfg 
[default]
callback_whitelist = skippy,profile_tasks,grafana_annotations

[callback_grafana_annotations]
grafana_url = "http://152.80.187.181/api/annotations"

ERROR! Unexpected Exception, this is probably a bug: set_options() got an unexpected keyword argument 'task_keys'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 90, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 209, in load_callbacks
    callback_obj .set_options(C.config.get_plugin_options('callback', callback_plugin._load_name))
  File "/var/lib/awx/projects/_59__sshgitgitlababc7999testgit_development/ansible/callback_plugins/grafana_annotations.py", line 155, in set_options
    super(CallbackModule, self).set_options(task_keys=task_keys, var_options=var_options, direct=direct)
TypeError: set_options() got an unexpected keyword argument 'task_keys'

**Comment by rrey** [comment]
hi @endejoli !

2.7.12 ? really ? :)

I realize that some changes were made directly on Ansible repository since the callback was merged in the project.
I just made a PR to back port the changes on this project but if you are using Ansible 2.7 you have to know that you don't need to checkout this code anymore since it is included in Ansible 2.6+

So if you remove the `callback_plugins/grafana_annotations.py`file from you project and keep the `ansible.cfg` section as is, it should work properly.

**Comment by endejoli** [comment]
damn, I copy pasted python version instead of ansible.  Ansible version is 2.4.1.0 :P

**Comment by endejoli** [comment]
Since 2.4 does not come with grafana_annotations.py, I had to use callback_plugins/grafana_annotations.py and I still get the error. Any suggestions?

**Comment by rrey** [comment]
Try to take what is now on master (I merged a patch a second ago).

I suspect your problem came from the `CALLBACK_VERSION` not being `2.0`. That was fixed on ansible repository, but never on my personal repo.

**Comment by endejoli** [comment]
Just tested, still the same issue. 
ERROR! Unexpected Exception, this is probably a bug: set_options() got an unexpected keyword argument 'task_keys'

**Comment by rrey** [comment]
I just checked the CallbackBase class from Ansible 2.4. the code of the set_options method only has one argument `options`.
So the callback won't work without some adaptations of the code.

You should upgrade your Ansible version, 2.4 is very far behind now ...

**Comment by endejoli** [comment]
Ok in some organization its not that easy to get tools upgraded, especially when things are not in our hands :). Is there anyway to get this working with this version ?

**Comment by rrey** [comment]
Probably.
You'll have to do some research to see what needs to be changed in the code.
I think that the `set_options` method is where you'll first have do change something.

I'm not really interested in supporting ansible 2.4, but if you want to do it and contribute to this project I'll happilly review your patch :)

**Comment by christidis** [comment]
Since this is deprecated in favor of ansible-collections I don't see any point contributing my patch here, unless you think I should.

In any case, I need this for a `2.4` Ansible installation so here is what I changed to make it work. I hope that helps.

```
>diff callback_plugins/grafana_annotations.py /tmp/grafana_annotations.orig.py 
184c184
<     def set_options(self, options):
---
>     def set_options(self, task_keys=None, var_options=None, direct=None):
186c186
<         super(CallbackModule, self).set_options(options)
---
>         super(CallbackModule, self).set_options(task_keys=task_keys, var_options=var_options, direct=direct)
188,195c188,195
<         self.grafana_api_key = self._plugin_options['grafana_api_key']
<         self.grafana_url = self._plugin_options['grafana_url']
<         self.validate_grafana_certs = self._plugin_options['validate_certs']
<         self.http_agent = self._plugin_options['http_agent']
<         self.grafana_user = self._plugin_options['grafana_user']
<         self.grafana_password = self._plugin_options['grafana_password']
<         self.dashboard_id = self._plugin_options['grafana_dashboard_id']
<         self.panel_ids = self._plugin_options['grafana_panel_ids']
---
>         self.grafana_api_key = self.get_option('grafana_api_key')
>         self.grafana_url = self.get_option('grafana_url')
>         self.validate_grafana_certs = self.get_option('validate_certs')
>         self.http_agent = self.get_option('http_agent')
>         self.grafana_user = self.get_option('grafana_user')
>         self.grafana_password = self.get_option('grafana_password')
>         self.dashboard_id = self.get_option('grafana_dashboard_id')
>         self.panel_ids = self.get_option('grafana_panel_ids')
```

Note: I modified [this](https://github.com/ansible-collections/grafana/blob/608949f8b72ae9d247e1716ec02da32f64264256/plugins/callback/grafana_annotations.py#L175) file from ansible-collections.

**Comment by rrey** [comment]
Hi @christidis !
Yeah it's going to be hard to merge this at all.
* This repository is useless now, and I should probably delete it.
* On ansible/ansible, since 2.4 is not maintained anymore, there is no branch where you could push your patch.
* Collections requires 2.9.x, so we are far ahead of 2.4
:(

Let's keep this repo alive with your diff for people who may have the same issue !
